name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run Docker container for testing
      run: docker run -d -p 5000:5000 myapp

    - name: Check container is running
      run: |
        sleep 3
        curl -v http://localhost:5000
